# In insert statement, add a newline after each comma.
comma-break=1

# Change the case of the reserved keyword. Default is uppercase: 2.
# Values: 0=>unchanged, 1=>lowercase, 2=>uppercase, 3=>capitalize.
keyword-case=2

# Change the case of the data type name. Default is lowercase: 1.
# Values: 0=>unchanged, 1=>lowercase, 2=>uppercase, 3=>capitalize.
type-case=1

# Change the case of the PostgreSQL functions. Default is unchanged: 0.
# Values: 0=>unchanged, 1=>lowercase, 2=>uppercase, 3=>capitalize.
function-case=2

# Do not add an extra empty line at end of the output.
no-extra-line=1

# Prevent sqlc function calls from being modified.
placeholder=sqlc\.(arg|embed|narg)\([^)]*\)

# Change space indent, default 4 spaces.
spaces=4

# Remove the space character between a function call and the open parenthesis that follows.
no-space-function=1

# Do not wrap function arguments onto new lines.
wrap-limit=0
