[tools]
go = "1.25.1"
node = "22"
"npm:prisma" = "6"
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "v1.29.0"

[env]
DATABASE_URL = "postgresql://postgres:postgres@localhost:5433/rls_example?sslmode=disable"
TEST_DATABASE_URL_BASE = "postgresql://postgres:postgres@localhost:5433"
TEST_DATABASE_NAME = "rls_example"

[task_config]
dir = "{{config_root}}/mise/tasks"
