// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const adminCreateLedgerEntry = `-- name: AdminCreateLedgerEntry :one
INSERT INTO ledger_entry (
    transfer_id,
    organization_id,
    amount,
    entry_type)
VALUES (
    $1,
    $2,
    $3,
    $4)
RETURNING
    id, transfer_id, amount, entry_type, created_at, organization_id
`

type AdminCreateLedgerEntryParams struct {
	TransferID     uuid.UUID
	OrganizationID uuid.UUID
	Amount         int32
	EntryType      string
}

func (q *Queries) AdminCreateLedgerEntry(ctx context.Context, arg *AdminCreateLedgerEntryParams) (*LedgerEntry, error) {
	row := q.db.QueryRow(ctx, adminCreateLedgerEntry,
		arg.TransferID,
		arg.OrganizationID,
		arg.Amount,
		arg.EntryType,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.Amount,
		&i.EntryType,
		&i.CreatedAt,
		&i.OrganizationID,
	)
	return &i, err
}

const adminCreateProgram = `-- name: AdminCreateProgram :one

INSERT INTO program (
    organization_id,
    name)
VALUES (
    $1,
    $2)
RETURNING
    id, organization_id, name, created_at, updated_at
`

type AdminCreateProgramParams struct {
	OrganizationID uuid.UUID
	Name           string
}

// Admin queries run under the app_system role (BYPASSRLS). They explicitly
// accept organization_id rather than relying on the session variable default.
// Used for seeding, backfills, cross-tenant background jobs, and migrations.
func (q *Queries) AdminCreateProgram(ctx context.Context, arg *AdminCreateProgramParams) (*Program, error) {
	row := q.db.QueryRow(ctx, adminCreateProgram, arg.OrganizationID, arg.Name)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const adminCreateTransfer = `-- name: AdminCreateTransfer :one
INSERT INTO transfer (
    id,
    program_id,
    organization_id,
    amount,
    description)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5)
RETURNING
    id, program_id, amount, description, created_at, updated_at, organization_id
`

type AdminCreateTransferParams struct {
	ID             uuid.UUID
	ProgramID      uuid.UUID
	OrganizationID uuid.UUID
	Amount         int32
	Description    *string
}

func (q *Queries) AdminCreateTransfer(ctx context.Context, arg *AdminCreateTransferParams) (*Transfer, error) {
	row := q.db.QueryRow(ctx, adminCreateTransfer,
		arg.ID,
		arg.ProgramID,
		arg.OrganizationID,
		arg.Amount,
		arg.Description,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.Amount,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return &i, err
}
