// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Email          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Project struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Description    *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
