// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type LedgerEntry struct {
	ID             uuid.UUID
	TransferID     uuid.UUID
	Amount         int32
	EntryType      string
	CreatedAt      time.Time
	OrganizationID uuid.UUID
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Program struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Transfer struct {
	ID             uuid.UUID
	ProgramID      uuid.UUID
	Amount         int32
	Description    *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	OrganizationID uuid.UUID
}
