// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO account (organization_id, email) VALUES ($1, $2) RETURNING id, organization_id, email, created_at, updated_at
`

type CreateAccountParams struct {
	OrganizationID uuid.UUID
	Email          string
}

func (q *Queries) CreateAccount(ctx context.Context, arg *CreateAccountParams) (*Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.OrganizationID, arg.Email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organization (id, name) VALUES ($1, $2) RETURNING id, name, created_at, updated_at
`

type CreateOrganizationParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateOrganization(ctx context.Context, arg *CreateOrganizationParams) (*Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.ID, arg.Name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO project (organization_id, name, description) VALUES ($1, $2, $3) RETURNING id, organization_id, name, description, created_at, updated_at
`

type CreateProjectParams struct {
	OrganizationID uuid.UUID
	Name           string
	Description    *string
}

func (q *Queries) CreateProject(ctx context.Context, arg *CreateProjectParams) (*Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.OrganizationID, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, organization_id, email, created_at, updated_at FROM account WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (*Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, created_at, updated_at FROM organization WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id uuid.UUID) (*Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getProject = `-- name: GetProject :one
SELECT id, organization_id, name, description, created_at, updated_at FROM project WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (*Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, organization_id, email, created_at, updated_at FROM account ORDER BY created_at
`

func (q *Queries) ListAccounts(ctx context.Context) ([]*Account, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, created_at, updated_at FROM organization ORDER BY created_at
`

func (q *Queries) ListOrganizations(ctx context.Context) ([]*Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, organization_id, name, description, created_at, updated_at FROM project ORDER BY created_at
`

func (q *Queries) ListProjects(ctx context.Context) ([]*Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
