// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO ledger_entry (transfer_id, amount, entry_type) VALUES ($1, $2, $3) RETURNING id, transfer_id, amount, entry_type, created_at, organization_id
`

type CreateLedgerEntryParams struct {
	TransferID uuid.UUID
	Amount     int32
	EntryType  string
}

// organization_id is auto-populated from the session variable via column default
func (q *Queries) CreateLedgerEntry(ctx context.Context, arg *CreateLedgerEntryParams) (*LedgerEntry, error) {
	row := q.db.QueryRow(ctx, createLedgerEntry, arg.TransferID, arg.Amount, arg.EntryType)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.Amount,
		&i.EntryType,
		&i.CreatedAt,
		&i.OrganizationID,
	)
	return &i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organization (id, name) VALUES ($1, $2) RETURNING id, name, created_at, updated_at
`

type CreateOrganizationParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateOrganization(ctx context.Context, arg *CreateOrganizationParams) (*Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.ID, arg.Name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createProgram = `-- name: CreateProgram :one
INSERT INTO program (organization_id, name) VALUES ($1, $2) RETURNING id, organization_id, name, created_at, updated_at
`

type CreateProgramParams struct {
	OrganizationID uuid.UUID
	Name           string
}

func (q *Queries) CreateProgram(ctx context.Context, arg *CreateProgramParams) (*Program, error) {
	row := q.db.QueryRow(ctx, createProgram, arg.OrganizationID, arg.Name)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfer (program_id, amount, description) VALUES ($1, $2, $3) RETURNING id, program_id, amount, description, created_at, updated_at, organization_id
`

type CreateTransferParams struct {
	ProgramID   uuid.UUID
	Amount      int32
	Description *string
}

// organization_id is auto-populated from the session variable via column default
func (q *Queries) CreateTransfer(ctx context.Context, arg *CreateTransferParams) (*Transfer, error) {
	row := q.db.QueryRow(ctx, createTransfer, arg.ProgramID, arg.Amount, arg.Description)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.Amount,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return &i, err
}

const getLedgerEntry = `-- name: GetLedgerEntry :one
SELECT id, transfer_id, amount, entry_type, created_at, organization_id FROM ledger_entry WHERE id = $1
`

func (q *Queries) GetLedgerEntry(ctx context.Context, id uuid.UUID) (*LedgerEntry, error) {
	row := q.db.QueryRow(ctx, getLedgerEntry, id)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.Amount,
		&i.EntryType,
		&i.CreatedAt,
		&i.OrganizationID,
	)
	return &i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, created_at, updated_at FROM organization WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id uuid.UUID) (*Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getProgram = `-- name: GetProgram :one
SELECT id, organization_id, name, created_at, updated_at FROM program WHERE id = $1
`

func (q *Queries) GetProgram(ctx context.Context, id uuid.UUID) (*Program, error) {
	row := q.db.QueryRow(ctx, getProgram, id)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getTransfer = `-- name: GetTransfer :one
SELECT id, program_id, amount, description, created_at, updated_at, organization_id FROM transfer WHERE id = $1
`

func (q *Queries) GetTransfer(ctx context.Context, id uuid.UUID) (*Transfer, error) {
	row := q.db.QueryRow(ctx, getTransfer, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.Amount,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return &i, err
}

const listLedgerEntries = `-- name: ListLedgerEntries :many
SELECT id, transfer_id, amount, entry_type, created_at, organization_id FROM ledger_entry ORDER BY created_at
`

func (q *Queries) ListLedgerEntries(ctx context.Context) ([]*LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.TransferID,
			&i.Amount,
			&i.EntryType,
			&i.CreatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, created_at, updated_at FROM organization ORDER BY created_at
`

func (q *Queries) ListOrganizations(ctx context.Context) ([]*Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrograms = `-- name: ListPrograms :many
SELECT id, organization_id, name, created_at, updated_at FROM program ORDER BY created_at
`

func (q *Queries) ListPrograms(ctx context.Context) ([]*Program, error) {
	rows, err := q.db.Query(ctx, listPrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Program
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfers = `-- name: ListTransfers :many
SELECT id, program_id, amount, description, created_at, updated_at, organization_id FROM transfer ORDER BY created_at
`

func (q *Queries) ListTransfers(ctx context.Context) ([]*Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Transfer
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.Amount,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
